#!/bin/bash
app=btsync_docker

# Remove NGINX conf
domain=$(sudo yunohost app setting $app domain)
sudo rm /etc/nginx/conf.d/$domain.d/$app.conf

# Remove container
sudo python remove_container.py
sudo rm -rf /home/yunohost.docker/container-$app

# Reload
sudo service nginx reload
sudo yunohost app ssowatconf 
